extract = 'total_dyn_inst: (\d+)'
benchmarks = './core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "./lvn",
    "./dce",
    "brili -p {args}",
]

[runs.pydce]
pipeline = [
    "bril2json",
    "python3 ../bril/examples/lvn.py",
    "python3 ../bril/examples/tdce.py tdce+",
    "brili -p {args}",
]
