extract = 'total_dyn_inst: (\d+)'
benchmarks = './core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "./lvn",
    "./dce",
    "brili -p {args}",
]

