extract = '\w*(\d+)'
benchmarks = '../bril/benchmarks/**/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "../task3/dce",
    "../task3/lvn",
    "../task3/dce",
    "bril2txt",
    "wc -l 1>&2",
]

[runs.ssa]
pipeline = [
    "bril2json",
    "../task3/dce",
    "../task3/lvn",
    "../task3/dce",
    "./ssa to",
    "../task3/dce",
    "../task3/lvn",
    "../task3/dce",
    "bril2txt",
    "wc -l 1>&2",
]

[runs.roundtrip]
pipeline = [
    "bril2json",
    "../task3/dce",
    "../task3/lvn",
    "../task3/dce",
    "./ssa to",
    "../task3/dce",
    "../task3/lvn",
    "../task3/dce",
    "./ssa from",
    "../task3/dce",
    "../task3/lvn",
    "../task3/dce",
    "bril2txt",
    "wc -l 1>&2",
]
