[envs.defined]
command = "bril2json < {filename} | ../df defined"
output."defined.out" = "-"

[envs.live]
command = "bril2json < {filename} | ../df live"
output."live.out" = "-"

[envs.reaching]
command = "bril2json < {filename} | ../df reaching"
output."reaching.out" = "-"
